#! /bin/bash
# Provided by azure extension which comes from template parameters
# use free to determine min/max heap sizes / setting min and max to the same

# need to set environment variables

CLUSTER_NAME=$1
CLUSTER_PASSWORD=$2

# used by maven to pull the hazelcast binary;however, services ignore environemnt variables.
sed -i 's/${env.CLUSTER_VERSION}/'"$3"'/g' pom.xml
CLUSTER_VERSION=$3
export CLUSTER_VERSION
sh -c 'echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> /etc/environment'

CLUSTER_SIZE=$4
LICENSEKEY=$5
MANCENTER_URL=$6
CUSTOM_JAR=$7

echo "Creating /var/hazelcast"
mkdir /var/hazelcast
#### check if custom_jar was provided and add it to the classpath
if [ "x$CUSTOM_JAR" != "x" ]
 then
   echo "A custom jar file was provided."
   wget "$CUSTOM_JAR" -O /var/hazelcast/custom.jar
   CLASSPATH=/var/hazelcast/custom.jar
   export CLASSPATH
   sh -c 'echo "CLASSPATH=$CLASSPATH" >> /etc/environment'
fi

chmod +x install_hazelcast
chmod +x modify_configuration
echo "modify_configuration"
./modify_configuration --license-key=$LICENSEKEY --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --cluster-version=$CLUSTER_VERSION --cluster-size=$CLUSTER_SIZE --man-url=$MANCENTER_URL --filename=hazelcast.xml
echo "install_hazelcast"
./install_hazelcast $CLUSTER_VERSION

echo "Starting hazelcast-server"
# service for upstart
cp ./hazelcast-server.conf /etc/init/ 2>>/dev/null
# service for systemd 
cp ./hazelcast-server.service /lib/systemd/system/ 2>>/dev/null
service hazelcast-server start
