#! /bin/bash
# Provided by azure extension which comes from template parameters
# use free to determine min/max heap sizes / setting min and max to the same

# need to set environment variables

CLUSTER_NAME=$1
CLUSTER_PASSWORD=$2

# used by maven to pull the hazelcast binary;however, services ignore environemnt variables.
sed -i 's/${env.CLUSTER_VERSION}/'"$3"'/g' pom.xml
CLUSTER_VERSION=$3
export CLUSTER_VERSION
sh -c 'echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> /etc/environment'

#### minimum heap size
MIN_HEAP_SIZE=`free | grep Mem | awk '{ printf(($2/1000000)*.20) }'`
if [ "x$MIN_HEAP_SIZE" = "x" ]
 then
   MIN_HEAP_SIZE=4G
fi
export MIN_HEAP_SIZE
sh -c 'echo "MIN_HEAP_SIZE=$MIN_HEAP_SIZE" >> /etc/environment'

MAX_HEAP_SIZE=`free | grep Mem | awk '{ printf($2/1000000) }'`
if [ "x$MAX_HEAP_SIZE" = "x" ]
 then
  MAX_HEAP_SIZE=4G
fi
export MAX_HEAP_SIZE
sh -c 'echo "MAX_HEAP_SIZE=$MAX_HEAP_SIZE" >> /etc/environment'

if [ "x$MIN_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MIN_HEAP_SIZE}g"
fi
if [ "x$MAX_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MAX_HEAP_SIZE}g"
fi
export JAVA_OPTS
# persist this variable to the VM environment
sh -c 'echo "JAVA_OPTIONS=$JAVA_OPTS" >> /etc/environment'

CLUSTER_SIZE=$4
CUSTOM_JAR=$5
SUBSCRIPTION_ID=$6

echo "Creating /var/hazelcast"
mkdir /var/hazelcast
#### check if custom_jar was provided and add it to the classpath
if [ "x$CUSTOM_JAR" != "x" ]
 then
   echo "A custom jar file was provided."
   wget "$CUSTOM_JAR" -O /var/hazelcast/custom.jar
   CLASSPATH=/var/hazelcast/custom.jar
   export CLASSPATH
   sh -c 'echo "CLASSPATH=$CLASSPATH" >> /etc/environment'
fi

chmod +x install_hazelcast
chmod +x modify_configuration
echo "modify_configuration"
./modify_configuration --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --cluster-version=$CLUSTER_VERSION --cluster-size=$CLUSTER_SIZE --filename=hazelcast.xml
echo "install_hazelcast"
./install_hazelcast $MIN_HEAP_SIZE $MAX_HEAP_SIZE $CLUSTER_VERSION

echo "Starting hazelcast-server"
cp ./hazelcast-server.conf /etc/init/
service hazelcast-server start
