#! /bin/bash

#assumes root/sudo user
apt-get update -y
apt-get install default-jdk -y
apt-get install maven -y
mvn install

#/var/hazelcast is created in bootstrap
cp pom.xml /var/hazelcast
cp ./hazelcast.xml /var/hazelcast/
