#! /bin/bash
# Provided by azure extension which comes from template parameters
# use free to determine min/max heap sizes / setting min and max to the same

# need to set environment variables

# used by maven to pull the hazelcast binary;however, services ignore environemnt variables.
sed -i 's/${env.CLUSTER_VERSION}/'"$3"'/g' pom.xml
CLUSTER_VERSION=$1
export CLUSTER_VERSION
sh -c 'echo "CLUSTER_VERSION=$CLUSTER_VERSION" >> /etc/environment'

LICENSEKEY=$2

echo "Creating /var/hazelcast"
mkdir /var/hazelcast

chmod +x install_hazelcast
chmod +x modify_configuration
echo "modify_configuration"
./modify_configuration --license-key=$LICENSEKEY --cluster-version=$CLUSTER_VERSION --filename=hazelcast.xml
echo "install_hazelcast"
./install_hazelcast $CLUSTER_VERSION

echo "Starting hazelcast-server"
# service for upstart
cp ./hazelcast-server.conf /etc/init/ 2>>/dev/null
# service for systemd 
cp ./hazelcast-server.service /lib/systemd/system/ 2>>/dev/null
service hazelcast-server start
